"""จัดวาง bubble หน้าแรกแบบ offline -> src/bubble_layout.h + preview PNG

วงใหญ่ (market cap สูง) กระจายก่อน แล้วอุดช่องว่างด้วยวงกลาง/เล็กให้ชิดที่สุด
แก้รายชื่อหุ้น/market cap แล้วรัน:  python tools/pack_bubbles.py
(ลำดับ CORE ต้องตรงกับ fetcher/fetch.py)
"""
import math
import os
import random
import sys

import numpy as np

W, H = 320, 224          # จอทั้งหมดลบแถบล่าง 16px
GAP = 2
R_MIN, R_MAX = 14, 48
SPREAD_FIRST = 8         # วงใหญ่ที่จะกระจายตัวก่อน

# ช่อง "core" = หุ้นท็อปตาม market cap (เรียงจากใหญ่ไปเล็ก ต้องตรงกับ CORE ใน fetcher/fetch.py)
# ชื่อใช้แค่ใน preview — เฟิร์มแวร์แสดงชื่อตามข้อมูลที่ได้รับ ช่องที่ i = หุ้นอันดับ i
CORE = [
    ("NVDA", 4500), ("MSFT", 3800), ("AAPL", 3700), ("GOOGL", 3000), ("AMZN", 2400),
    ("META", 1900), ("AVGO", 1600), ("TSLA", 1300), ("BRK.B", 1050), ("JPM", 820),
    ("WMT", 800), ("LLY", 780), ("ORCL", 700), ("V", 680), ("MA", 530),
    ("NFLX", 500), ("XOM", 480), ("COST", 430), ("PLTR", 420), ("JNJ", 400),
    ("HD", 380), ("PG", 360), ("AMD", 350), ("ABBV", 350), ("BAC", 340),
]
# ช่อง "hot" = หุ้นร้อนแรงของวัน อันดับ 1 วงใหญ่สุด (ค่า = market cap สมมติเพื่อกำหนดขนาด)
HOT = [900, 760, 650, 560, 500, 450, 400, 370, 340, 310, 290, 270, 250, 230, 210]
STOCKS = CORE + [(f"HOT{i + 1}", c) for i, c in enumerate(HOT)]


def radii(scale):
    caps = np.array([c for _, c in STOCKS], float)
    r = scale * caps ** 0.5
    return np.clip(np.round(r), R_MIN, R_MAX).astype(int)


def relax(rs, seed, iters=2500):
    """จำลองฟิสิกส์: สุ่มตำแหน่ง -> ดันวงที่ทับกันออก + ดึงเข้ากลางเบาๆ คืน (xy, overlap สูงสุด)"""
    rng = np.random.default_rng(seed)
    n = len(rs)
    r = rs.astype(float)
    xy = np.column_stack([rng.uniform(r, W - r), rng.uniform(r, H - r)])
    mass = r ** 2
    for it in range(iters):
        d = xy[:, None, :] - xy[None, :, :]
        dist = np.hypot(d[..., 0], d[..., 1]) + np.eye(n)
        need = r[:, None] + r[None, :] + GAP
        ov = np.clip(need - dist, 0, None)
        np.fill_diagonal(ov, 0)
        # วงเล็กขยับมากกว่าวงใหญ่
        w = mass[None, :] / (mass[:, None] + mass[None, :])
        push = (d / dist[..., None]) * (ov * w)[..., None]
        xy += push.sum(axis=1) * 0.5
        if it < iters * 0.7:
            xy += (np.array([W / 2, H / 2]) - xy) * 0.002  # ให้อัดแน่น
        xy[:, 0] = np.clip(xy[:, 0], r, W - 1 - r)
        xy[:, 1] = np.clip(xy[:, 1], r, H - 1 - r)
    d = xy[:, None, :] - xy[None, :, :]
    dist = np.hypot(d[..., 0], d[..., 1]) + np.eye(n) * 1e9
    worst = (r[:, None] + r[None, :] + GAP - dist).max()
    return xy, worst


def grow(xy, rs):
    """ขยายแต่ละวงเข้าไปในที่ว่าง (ไม่เกิน R_MAX และไม่เกิน 1.3 เท่า)"""
    rs = rs.copy()
    for _ in range(4):
        for i in np.argsort(-rs):
            x, y = xy[i]
            room = min(x, W - 1 - x, y, H - 1 - y)
            for j in range(len(rs)):
                if j != i:
                    room = min(room, math.hypot(x - xy[j][0], y - xy[j][1]) - rs[j] - GAP)
            rs[i] = int(min(max(rs[i], math.floor(room)), R_MAX, rs[i] * 1.3 + 1))
    return rs


def pack(scale, seed):
    rs = radii(scale)
    best = None
    for s in range(seed, seed + 6):
        xy, worst = relax(rs, s)
        if worst <= 0.5 and (best is None):
            best = xy
    if best is None:
        return None
    xy = np.round(best).astype(int)
    rs = grow(xy, rs)
    return {i: (int(xy[i][0]), int(xy[i][1]), int(rs[i])) for i in range(len(rs))}


def main():
    scale = 1.1
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 7
    while True:
        res = pack(scale, seed)
        if res:
            break
        scale *= 0.97
    fill = sum(math.pi * r * r for _, _, r in res.values()) / (W * H)
    print(f"scale={scale:.3f} fill={fill:.0%}")

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(root, "src", "bubble_layout.h"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/pack_bubbles.py — อย่าแก้มือ\n#pragma once\n#include <stdint.h>\n\n")
        f.write("struct BubbleSlot {\n  int16_t cx, cy, r;\n};\n\n")
        f.write(f"constexpr int BUBBLE_CORE = {len(CORE)};  // ช่อง 0.. = หุ้นท็อปตาม market cap\n")
        f.write(f"constexpr int BUBBLE_HOT = {len(HOT)};    // ช่องถัดไป = หุ้นร้อนแรง (ใหญ่ -> เล็ก)\n")
        f.write("constexpr int BUBBLE_COUNT = BUBBLE_CORE + BUBBLE_HOT;\n")
        f.write("static const BubbleSlot BUBBLES[BUBBLE_COUNT] = {\n")
        for i, (s, _) in enumerate(STOCKS):
            x, y, r = res[i]
            f.write(f"    {{{x}, {y}, {r}}},  // {s}\n")
        f.write("};\n")

    try:
        from PIL import Image, ImageDraw
        img = Image.new("RGB", (W * 3, H * 3), (5, 7, 10))
        d = ImageDraw.Draw(img)
        rnd = random.Random(1)
        for i, (s, _) in enumerate(STOCKS):
            x, y, r = res[i]
            up = rnd.random() > 0.45
            for k in range(r * 3, 0, -1):  # radial gradient คร่าวๆ
                t = k / (r * 3)
                a = 0.12 if t < 0.55 else (0.12 + (t - 0.55) / 0.4 * 0.88 if t < 0.95 else 1)
                col = (int(16 * a), int(255 * a), int(48 * a)) if up else (int(255 * a), int(16 * a), int(16 * a))
                d.ellipse([x * 3 - k, y * 3 - k, x * 3 + k, y * 3 + k], fill=col)
            d.text((x * 3, y * 3), s, fill=(255, 160, 40) if s.startswith("HOT") else "white", anchor="mm")
        img.save(os.path.join(root, "docs", "bubbles_preview.png"))
    except ImportError:
        pass


if __name__ == "__main__":
    main()
