// generated by tools/pack_bubbles.py — อย่าแก้มือ
#pragma once
#include <stdint.h>

struct BubbleSlot {
  int16_t cx, cy, r;
};

constexpr int BUBBLE_CORE = 25;  // ช่อง 0.. = หุ้นท็อปตาม market cap
constexpr int BUBBLE_HOT = 15;    // ช่องถัดไป = หุ้นร้อนแรง (ใหญ่ -> เล็ก)
constexpr int BUBBLE_COUNT = BUBBLE_CORE + BUBBLE_HOT;
static const BubbleSlot BUBBLES[BUBBLE_COUNT] = {
    {95, 81, 43},  // NVDA
    {183, 64, 39},  // MSFT
    {231, 128, 39},  // AAPL
    {36, 144, 35},  // GOOGL
    {84, 192, 31},  // AMZN
    {291, 164, 28},  // META
    {25, 83, 25},  // AVGO
    {57, 23, 23},  // TSLA
    {298, 61, 21},  // BRK.B
    {223, 205, 18},  // JPM
    {129, 167, 18},  // WMT
    {197, 177, 18},  // LLY
    {234, 32, 17},  // ORCL
    {134, 33, 17},  // V
    {37, 196, 15},  // MA
    {285, 120, 14},  // NFLX
    {274, 90, 14},  // XOM
    {175, 118, 14},  // COST
    {266, 43, 14},  // PLTR
    {206, 14, 14},  // JNJ
    {292, 23, 15},  // HD
    {157, 202, 14},  // PG
    {180, 148, 14},  // AMD
    {161, 14, 14},  // ABBV
    {162, 172, 14},  // BAC
    {243, 70, 19},  // HOT1
    {100, 18, 18},  // HOT2
    {266, 206, 16},  // HOT3
    {299, 208, 15},  // HOT4
    {14, 14, 14},  // HOT5
    {186, 209, 14},  // HOT6
    {145, 111, 14},  // HOT7
    {24, 42, 14},  // HOT8
    {261, 14, 14},  // HOT9
    {151, 141, 14},  // HOT10
    {92, 140, 14},  // HOT11
    {247, 181, 14},  // HOT12
    {128, 209, 14},  // HOT13
    {305, 98, 14},  // HOT14
    {121, 134, 14},  // HOT15
};
